management:
#  endpoint:
#    shutdown:
#      enabled: true
#  endpoints:
#    jmx:
#      exposure:
#        include: "health,info"

  endpoint:
    health:
      show-components: always

  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"  ## 해당 엔드포인트 제외
      ##base-path: "/manage"

  info:
    ## java, os, env info
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

    ## git info
    git:
      mode: "full"

#  server:
#    port: 9292

info:
  app:
    name: hello-actuator
    company: mykim

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true